platform :ios , '8.0'
target '生命灵数' do
    pod 'WRNavigationBar','~>1.0.9’
    pod 'SDAutoLayout'
    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'RongCloudIM/IMKit', '~> 2.8.3'
    pod 'AFNetworking'
    pod 'Reachability'
    pod 'MBProgressHUD'
end
